### ISSUE TITLE
Fine-tune my custom data

### ISSUE THREAD

**Issue by whoafridi** [cjaniake/squad_v2.0_pt#1]
Great after all.

I've specific questions. There is a model sagorsarker/bangla-bert-base already available for Bengali language, also a squad like dataset from google tydiqa contains questions of Bengali. So, is it possible to finetune with the model & dataset ???
run_squad.py is valid for it ?as simple as that or i Use run_squad_trainer.py ?(updated script) from huggingface repo
Any tutorials for finu-tune my own model very easily. It'll really helpful
Thank you.

**Comment by cjaniake** [comment]
Sure, you could use the run_squad.py script from the BERT repo (https://github.com/google-research/bert) or you could use the run_squad.py or run_squad_trainer.py from Hugging Face Transformers repo. If you intend to run it on **Google Colab** and use **TPU** for training you should choose the **run_squad_trainer.py**, and you probably will need to use the Colab Pro to get the resources you need. But if you have an available GPU it would be easier to run locally, just run the script and it should work.
